### ISSUE TITLE
UML diagram

### ISSUE THREAD

**Issue by 492793425** [TheHiddenFaker/2020-GPW-L5K2-A#12]

**Comment by 492793425** [comment]
I already finished use case diagram
[use case diagram.docx](https://github.com/TheHiddenFaker/2020-GPW-L5K2-A/files/4537634/use.case.diagram.docx)

**Comment by jslemmer** [comment]
Maybe you can add a picture of it here, so it is easier to view

**Comment by TheHiddenFaker** [comment]
![erd](https://user-images.githubusercontent.com/45250648/81530259-18933e80-9393-11ea-8e84-8c8f669c71bc.png)
I have created the basic ERD diagram. And you can give me feedback.

**Comment by xinyanzu1** [comment]
emmm

**Comment by 492793425** [comment]
it‘s good work

**Comment by xinyanzu1** [comment]
I think ERD need add attribute
