### ISSUE TITLE
Detailed Planning Disscussion

### ISSUE THREAD

**Issue by TheHiddenFaker** [TheHiddenFaker/2020-GPW-L5K2-A#4]

**Comment by TheHiddenFaker** [comment]
For the sprint1, we have to focus on the prototypes.

**Comment by 492793425** [comment]
I think the first stage should be to discuss what functionality needs to be implemented. And prioritize them.

**Comment by TheHiddenFaker** [comment]
So, we can focus two parts: requirements and prototypes.

**Comment by 492793425** [comment]
Task
1. Create a prototype of your sales system user interface and a prototype of
your management system user interface. (3 rounds of improvements)
2. Create a suitable database structure (.sql)
3. Create a working system (PHP, HTML, CSS, MYSQL)

**Comment by TheHiddenFaker** [comment]
Which prototype interfaces should be completed for the two systems?

**Comment by 492793425** [comment]
### **Function**
First, we need to make three interfaces.User sales interface, route management interface and senior manager interface.
**Customer function**
1. Information addition
2. Buy a bus ticket
3. Change your password
4. User login interface and sign interface
**Route scheduling personnel function**
1. The administrator schedules the route.
2. Login interface
**Senior manager interface**
1. Login interface
2. Panel: shows the sales volume and some performance information of the whole company and the total number of customers
3. Manage distribution routes
4. Modify and view user information
5. Manage employee information
6. Change anyone's password

**Comment by TheHiddenFaker** [comment]
So, that is sprint 1. How about the sprint 2?

**Comment by 492793425** [comment]
Sprint 2: Prototype Improvements and Database Structure

**Comment by TheHiddenFaker** [comment]
And for the sprint 3, we can still improve the prototypes and turn to coding about sale system.

**Comment by 492793425** [comment]
I think the sprint2 should start by Prototype Improvements and analyzing the requirements and structure of the system.The method applied to UML.

**Comment by 492793425** [comment]
**ALL phase task**
Sprint 1: Product Backlog and Prototype Design
Sprint2: Prototype Improvements and analyzing the requirements and structure of the system.
Sprint3: Still improve the prototypes and Database Structure
Sprint4: Still improve the prototypes and turn to coding about sale system and homepage.
Sprint5: Administrative personnel hierarchical login interface and system.
Sprint6: Test system functionality and check database logic.

**Comment by xinyanzu1** [comment]
I think these tasks are almost enough now

**Comment by 492793425** [comment]
What does the group leader think?

**Comment by TheHiddenFaker** [comment]
The sprint 4 and 5 should be more specific.

**Comment by xinyanzu1** [comment]
what's more, checking the database logic should be done at the time of establishment in sprint 6

**Comment by xinyanzu1** [comment]
How is our task assigned this week, Bruce
