### ISSUE TITLE
Product backlog

### ISSUE THREAD

**Issue by TheHiddenFaker** [TheHiddenFaker/2020-GPW-L5K2-A#5]

**Comment by 492793425** [comment]
I'll finish it, no problem

**Comment by 492793425** [comment]
I finished it. I will send the diagram to project

**Comment by 492793425** [comment]
[Product Backlog for Bus Information System.docx](https://github.com/TheHiddenFaker/2020-GPW-L5K2-A/files/4499590/Product.Backlog.for.Bus.Information.System.docx)
[Product Backlog for Bus Information System.docx](https://github.com/TheHiddenFaker/2020-GPW-L5K2-A/files/4499591/Product.Backlog.for.Bus.Information.System.docx)

**Comment by TheHiddenFaker** [comment]
The PB have some issues: 
1. Not detailed.
2. Some items are unmatched with the Appendix requirements.
3. Some items are extra functions for the system.
