### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by TheHiddenFaker** [TheHiddenFaker/2020-GPW-L5K2-A#8]

**Comment by TheHiddenFaker** [comment]
![image](https://user-images.githubusercontent.com/45250648/80328879-3fba1e00-8873-11ea-9381-f215f14f5c4e.png)
I already finished the login page design.

**Comment by xinyanzu1** [comment]
I think that we don't need login with Google and Facebook

**Comment by TheHiddenFaker** [comment]
Those two buttoms will be removed in the actual file.
